### ISSUE TITLE
Installation instructions failing on Fedora

### ISSUE THREAD

**Issue by mberube99** [konveyor/crane-documentation#4]
# curl -sL https://api.github.com/repos/konveyor/crane/releases/latest | jq -r ".assets[] | select(.name | contains(\"<arch>-<os>\")) | .browser_download_url" | wget -i-

No URLs found in -.

**Comment by mberube99** [comment]
# curl -sL https://api.github.com/repos/konveyor/crane/releases/latest |grep browser_download_url
      "browser_download_url": "https://github.com/konveyor/crane/releases/download/v0.0.2/amd64-darwin-crane-v0.0.2"
      "browser_download_url": "https://github.com/konveyor/crane/releases/download/v0.0.2/amd64-linux-crane-v0.0.2"
      "browser_download_url": "https://github.com/konveyor/crane/releases/download/v0.0.2/arm64-darwin-crane-v0.0.2"

Looks like the error is in the jq command as I can get the download URL from curl and grep ^^^^

**Comment by JaydipGabani** [comment]
@mberube99 Thanks for the issue.

The correct usage of the command would be - 

```
curl -sL https://api.github.com/repos/konveyor/crane/releases/latest | jq -r ".assets[] | select(.name | contains(\"amd64-linux\")) | .browser_download_url" | wget -i-
```
or
```
curl -sL https://api.github.com/repos/konveyor/crane/releases/latest | jq -r ".assets[] | select(.name | contains(\"arm64-darwin\")) | .browser_download_url" | wget -i-
```
or
```
curl -sL https://api.github.com/repos/konveyor/crane/releases/latest | jq -r ".assets[] | select(.name | contains(\"amd64-darwin\")) | .browser_download_url" | wget -i-
```

**Comment by jmontleon** [comment]
You can also just run `dnf -y install hugo` for Fedora...

**Comment by JaydipGabani** [comment]
Closing this as PR is merged
